/** @format */

import "@/styles/globals.css";
import "react-multi-carousel/lib/styles.css";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import Provider from "@/provider";
import SideBar from "@/components/sidebar";
import Tabs from "@/components/tabs";
import ScrollProvider from "@/scroll-provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: 0,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen antialiased scroll-py-9 lg:scroll-py-16 snap-y",
        inter.className
      )}
    >
      <body
        suppressHydrationWarning={true}
        className="min-h-screen antialiased w-full overflow-x-hidden overflow-y-scroll bg-primary-black"
      >
        <ScrollProvider>
          <div className="relative container max-w-7xl mx-auto h-full px-[22px] md:px-[2rem] py-[2rem]">
            <div className="flex flex-col w-full lg:flex-row">
              <div className="mx-auto lg:ml-0 w-[350px] hidden lg:flex lg:w-[350px] relative lg:fixed z-40 flex-col border-[#717070] px-6 py-7 rounded-xl border-[0.1px] drop-shadow-md shadow-lg">
                <SideBar />
              </div>
              <main className="lg:ml-[350px] xl:ml-[330px] lg:max-w-2xl xl:max-w-3xl h-full w-full">
                <Provider>
                  <div className="flex flex-col w-full">
                    <div className="flex flex-col ml-auto mr-[35px] sm:mr-[15px] md:mr-[35px] z-50">
                      <Navbar />
                    </div>
                    <div className="hidden sm:flex flex-col ml-auto mr-[20px] sm:mr-[15px] md:mr-[35px] z-50">
                      <div className="top-[260px] fixed z-50 bg-[#262626] md:bg-transparent border-[#717070] border-[0.1px] rounded-3xl drop-shadow-md shadow-lg">
                        <Tabs />
                      </div>
                    </div>
                    <div className="pt-8">{children}</div>
                  </div>
                </Provider>
              </main>
            </div>
          </div>
        </ScrollProvider>
        <Toaster />
      </body>
    </html>
  );
}
